name: KWorld
version: 1.0
author: KosmosUniverse
main: fr.kosmosuniverse.kworld.KWorldMain
api-version: 1.13

commands:
  kguide:
    description: command to get the plugin guide
    usage: /kguide
  kgive:
    description: command to get the plugin custom items
    permission: kgive.use
    usage: /kgive item
  kspawn:
    description: Command to spawn plugin Multiblocks
    permission: kspawn.use
    usage: /kspawn MultiBlock